---
title: "R Notebook"
output: html_notebook
---

```{r setup, echo=FALSE}
library('tidyverse')
library('ggpubr')
```


# Load it up

```{r load_behav}
datapath  <- '~/Desktop/behavior/'
datafiles <- list.files(datapath, pattern='.*EmoRet.*\\.csv', 
                        full.names=TRUE, 
                        recursive=TRUE)
df.behav        <- do.call(rbind, lapply(datafiles, read.csv))
```

```{r load_roi}
datapath  <- '~/Desktop/ER_SubEmoMemParMod/OneSampleTs18/0005_Emotional-Trials_vs_Neutral-Trials/'
(df.roi    <- read.csv(paste0(datapath, 'roi-data.csv')))
```

# Calculate Memory Performance

```{r extract_subjectID}
# extract subjectIDs from the files names and add them as a factor column of `df`
matches           <- regexpr ('sub-s[0-9]{3}', datafiles, perl = T)
subjectIDs        <- regmatches(datafiles, matches)
lengths           <- lapply(lapply(datafiles, read.csv), nrow)
df.behav$subjects <- factor(rep(subjectIDs, each = unique(lengths)))
```


```{r calculate_memory}
(df.behav %>%
  group_by(subjects) %>%
  summarize(emo_source_memory_performance = mean(EmoAccuracy)) -> df.behav)

```

# Brain-Behavior Relation

```{r combine_dataframes}
(left_join(df.roi, df.behav, by = "subjects") %>%
  select(one_of(c("subjects", "left_caudate", "right_caudate", "emo_source_memory_performance"))) %>%
  mutate(subjects = factor(subjects)) %>%
  gather("roi", "negative_>_neutral", left_caudate, right_caudate) %>%
  mutate(roi = factor(roi)) -> df.brain.behavior)
```

```{r plot}
# left caudate
bv <- df.brain.behavior$roi  == "left_caudate"
left_caudate.test <- cor.test(df.brain.behavior$emo_source_memory_performance[bv],
                              df.brain.behavior$`negative_>_neutral`[bv])
# right caudate
bv <- df.brain.behavior$roi  == "right_caudate"
right_caudate.test <- cor.test(df.brain.behavior$emo_source_memory_performance[bv],
                              df.brain.behavior$`negative_>_neutral`[bv])

df.brain.behavior %>%
  group_by(roi) %>%
  mutate(cor = as.character(round(ifelse(roi == "left_caudate", left_caudate.test$estimate[[1]], 
                      ifelse(roi == "right_caudate", right_caudate.test$estimate[[1]], NA)), 3)),
         p.value = as.character(round(ifelse(roi == "left_caudate", left_caudate.test$p.value[[1]], 
                      ifelse(roi == "right_caudate", right_caudate.test$p.value[[1]], NA)), 3))
         ) -> df.brain.behavior

df.brain.behavior %>%
  ggplot(aes(x = emo_source_memory_performance, y = `negative_>_neutral`)) + 
  geom_point() + 
  geom_smooth(method='lm', se = FALSE) + 
  geom_label(aes(x = .81, y = 1, label = paste0("corr: ", cor, " p=", p.value))) + 
  facet_grid(~roi) + 
  ggtitle("Brain-Behavior Correlation", 
          subtitle = "Negative Trials > Neutral Trials x Subsequent Source Memory Performance") + 
  ylab("Beta Estimate\nNegative Trials > Neutral Trials") + 
  xlab("Subsequent Emotional Memory Peformance")
```

